import { NavBar } from "@/components/NavBar/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="font-sans min-h-[100vh]">
          <NavBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
